### ISSUE TITLE
Add database migration

### ISSUE THREAD

**Issue by mamadaliev** [reckue/authorization-service-api#47]
**AS A** developer,
**I WANT** to be able to migrate the database.

**ACCEPTANCE CRITERIA:**

1. Provide ablility to migrate data in DB.
1.1. Add Liqueabase dependency and configure it.
1.2. Add examples for working with migration.
1.3. Use YAML format.

**Comment by mamadaliev** [comment]
BE 2

**Comment by camelya58** [comment]
Closed
